### ISSUE TITLE
Bug: Enters a blank site when previous button is clicked while playing Wordle Archive 1

### ISSUE THREAD

**Issue by aghogwarts** [DevangThakkar/wordle_archive#1]
When we click the previous button when the Wordle Archive 1 is loaded, a blank page appears. Although when it's reloaded, it goes back to a random wordle, you could fix this so that the previous button gets greyed out when playing Wordle Archive 1

**Comment by DevangThakkar** [comment]
That's a good catch @aghogwarts! I've fixed it by having nothing happen if you click previous on Day 1 (similar to clicking next on the current day). Thanks for reporting the bug!

**Comment by aghogwarts** [comment]
No problem, that's a nice fix. This project is amazingly done with the UI of your archive being smoother and better than that of the actual Wordle. Kudos!

**Comment by DevangThakkar** [comment]
Thanks! A lot of this project is built on top of the UI of https://octokatherine.github.io/word-master/
