### ISSUE TITLE
URL for each puzzle

### ISSUE THREAD

**Issue by denishowe** [DevangThakkar/wordle_archive#12]
Thanks for creating this.  It would be great if each puzzle had its own URL, e.g. https://www.devangthakkar.com/wordle_archive/42 so you could, e.g. bookmark the one you've got up to.  Want a PR for this?

**Comment by DevangThakkar** [comment]
Sure, that would be great! Thanks for working on this. :)

**Comment by denishowe** [comment]
PR created.  Let me know if you get a chance to look at it.  Cheers.

**Comment by DevangThakkar** [comment]
Thanks for working on this. Closing this.
