### ISSUE TITLE
Different share content based on theme

### ISSUE THREAD

**Issue by rdatta95** [DevangThakkar/wordle_archive#13]
The wordle site uses different icons for the invalid letters based on the theme when sharing
Can we have something like that here as well?

**Light Theme**

Wordle 219 4/6

⬜🟨⬜⬜🟨
⬜🟨🟨⬜🟨
⬜🟩⬜⬜🟩
🟩🟩🟩🟩🟩 

**Dark Theme**

Wordle 219 4/6

⬛🟨⬛⬛🟨
⬛🟨🟨⬛🟨
⬛🟩⬛⬛🟩
🟩🟩🟩🟩🟩

**Comment by DevangThakkar** [comment]
Sure, that's a good suggestion. I'll work on it.

**Comment by rdatta95** [comment]
Thank you!

**Comment by DevangThakkar** [comment]
This is now implemented, check it out! Closing this for now.
