### ISSUE TITLE
Include Wordle 0

### ISSUE THREAD

**Issue by IAmKatharineC** [DevangThakkar/wordle_archive#14]
Wordle follows array numbering so there is a solution for day 0 available which isn't in this version. 

Please consider adding this as the first puzzle. I have the answer word available - I won't add it here in case it is considered a spoiler, but please get in touch if you would like the information.

**Comment by DevangThakkar** [comment]
I do have access to the zeroth answer, thanks! I would be down to add it but I think it would mess up with my system for storing records of completed wordles, which is something I would like to avoid. I appreciate the suggestion though.
