### ISSUE TITLE
Nada

### ISSUE THREAD

**Issue by llbarrows** [DevangThakkar/wordle_archive#16]
I entered all vowels to start with and nothing happens

**Comment by DevangThakkar** [comment]
Hi, the entered word needs to be a valid word. What word are you using?

**Comment by llbarrows** [comment]
Sorry, this is my first time doing this. It wasn't a word, just weigh looking for vowels. Ill try again. Thank you


"... a long habit of not thinking a thing wrong 
gives it a superficial appearance of being right..."

~ Thomas Paine

     On Monday, January 24, 2022, 09:43:35 PM CST, Devang Thakkar ***@***.***> wrote:  
 
 


Hi, the entered word needs to be a valid word. What word are you using?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DevangThakkar** [comment]
No worries! Closing this for now.
