### ISSUE TITLE
Button to reenter share screen

### ISSUE THREAD

**Issue by rdatta95** [DevangThakkar/wordle_archive#17]
Currently the option to share comes only after completing the puzzle, but cannot be accessed again once that screen is closed.
A possible workaround is taking a screenshot of the guesses, restarting the puzzle, and making the same guesses again to get to the same result screen.
A button to get to the share screen would be nice.

Maybe it's not a necessary feature, but it is a good-to-have QOL feature.

**Comment by DevangThakkar** [comment]
This is now implemented, check it out! Closing this for now.
