### ISSUE TITLE
Letter showing as both "matching" and "excluded"

### ISSUE THREAD

**Issue by globau** [DevangThakkar/wordle_archive#19]
Guessing KNOWN for https://www.devangthakkar.com/wordle_archive/?219 results in:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/872825/151100914-6313b55a-7543-4c7a-8d5f-1b8079821cd3.png">

`N` is both "in the correct spot" and "not in the word in any spot".  I'm not sure what official Wordle does, but I would expect the `N` in position 5 to be "in the word but in the wrong spot" with a yellow background.

**Comment by DevangThakkar** [comment]
Hi, the protocol for this is the same as the official Wordle. If a letter is in the correct place, it is marked as green. If you repeat a letter, the repeated letter in the wrong place will only be marked yellow if the letter is also in another place in the word. Check out this example from the original Wordle webpage - the word is SUGAR and guessing SHUSH only marks the first S as green, the second is marked as gray. You can confirm this by trying HELLO for 219.

![image](https://user-images.githubusercontent.com/6257460/151103675-9f366f4f-5a06-4230-8ea1-5747819f10e0.png)

**Comment by globau** [comment]
Ahh, thank you for the explanation!
