### ISSUE TITLE
[Feature Request] store progress/solutions in localStorage

### ISSUE THREAD

**Issue by EhsanKia** [DevangThakkar/wordle_archive#2]
The official world site keeps your progress upon refresh. Something similar would be nice, could probably store the state in localStorage for each day, and restore it if found (partial or complete). Could have a button to reset if needed.

I'd be happy to implement it myself this weekend, let me know what you think of the feature. I want to go through and complete all of them, but would like to keep my progress stored so I remember how I did on each.

**Comment by DevangThakkar** [comment]
I think that is a good idea! Feel free to implement this and we can review/merge it once you are done. Thanks a lot!

**Comment by DevangThakkar** [comment]
I've implemented this with my recent commit. The website now stores what wordles you have already finished. Closing this.
