### ISSUE TITLE
Bug in tile colors?

### ISSUE THREAD

**Issue by saund** [DevangThakkar/wordle_archive#20]
I think there may be a bug in the tile colors.
In game number 151, the answer word is HERON.
If you enter the probe word, ERROR, Wordle Archive marks
that as

     E        R         R        O        R
Yellow  Gray  Green Green  Gray

But the Gray tiles are for the letter R which does occur in the word.

Isn't the correct tile color response:

    E         R         R         O       R
Yellow Yellow Green Green Yellow

    H        E          R        O       N

![image](https://user-images.githubusercontent.com/4144043/151223243-ef904ce2-d3b9-4dbd-861a-f22a802589a4.png)

**Comment by DevangThakkar** [comment]
Hi, the protocol for this is the same as the official Wordle. If a letter is in the correct place, it is marked as green. If you repeat a letter, the repeated letter in the wrong place will only be marked yellow if the letter is also in another place in the word. Check out this example from the original Wordle webpage for today, i.e. 221 - the word is WHACK and guessing CHUCK only marks the second C as green, the first is marked as gray.

**Comment by saund** [comment]
Great!  Thank you for clarifying that.

**Comment by DevangThakkar** [comment]
No worries! Closing this for now.
