### ISSUE TITLE
Feature Request: Score Log

### ISSUE THREAD

**Issue by ranemartin8** [DevangThakkar/wordle_archive#21]
It would be awesome if you could see your score on the Wordles you completed, like on this other Wordle Archive (screenshot below): https://metzger.media/games/wordle-archive/ 

Like maybe in the "Choose" dropdown next to the Completed check mark.

![image](https://user-images.githubusercontent.com/22800045/151453251-ff67a6d1-ac28-4eb6-bf40-fa164ef009b1.png)

.

**Comment by DevangThakkar** [comment]
Yep, that's a good suggestion, I'll take a look into it.
