### ISSUE TITLE
Wordle history

### ISSUE THREAD

**Issue by Danny-Engelman** [DevangThakkar/wordle_archive#23]
Since there is no copyright on Josh Wardle his code **and** he built Wordle with native JavaScript Web Components;
you could have **_extended_** the original Web Component, and built a version that plays all words backward in time:
https://github.com/mordle/mordle.github.io

**Comment by DevangThakkar** [comment]
That sounds great, kudos on a job well done! I did find a few issues trying to play it though. I clicked play previous wordle in the stats pop-up and it led me to Day -1, the word for which was UNDEFINED. Adding navigation would definitely make it awesome-r.

![image](https://user-images.githubusercontent.com/6257460/151648219-380a3182-4b4b-4d51-8215-e71df4c455a9.png)

Closing this for now!
