### ISSUE TITLE
BUG: Some sequence of keys adds an extra box, breaks interface

### ISSUE THREAD

**Issue by Clhamlin** [DevangThakkar/wordle_archive#27]
**I have not been able to reproduce**

I ended up in a broken state after submitting an invalid word where an extra box was inserted. 

1. Guessed 3 words
2. Typed in an invalid word on the 4th word
2. Hit enter (and I believe close to simultaneously spacebar) 
3. The word was marked as invalid
4. An extra box was inserted after the last box of the 4th word
5. Submitted a valid 4th word
6. Started typing the 5th word
7. The first letter of the 5th word appeared in the second box from the left of the 5th row instead of the first
8. Opened developer console, deleted broken box span element (I did not look closely at or copy it first unfortunately)
9. Finished game
10. Clicked next and got a blank screen
11. Refreshed and everything was fine 

This was probably just a fluke that's not worth chasing down but I figured I'd mention it since as a web developer I was curious

![image](https://user-images.githubusercontent.com/5818359/151671730-c392fe35-b914-4c32-b198-ba8ee734a48c.png)

**Comment by DevangThakkar** [comment]
Hmm, that is very weird! I honestly have no idea how this happened but it seems pretty innocuous if it's not reproducible/recurring. Thanks for reporting it nevertheless!
