### ISSUE TITLE
BUG: Puzzle 3 has no solution

### ISSUE THREAD

**Issue by manevarthe** [DevangThakkar/wordle_archive#28]
I identified 4 letters with correct positions. And tried with all remaining alphabets for the 5th letter, but none of them fit (_Note: 5th letter doesn't mean 5th position_).

**Comment by DevangThakkar** [comment]
Hi, the solution is HUMPH, like an exclamation used to express slightly scornful doubt or dissatisfaction. What do you have so far?

**Comment by manevarthe** [comment]
Aah! Somehow I didn't think about reusing same letter twice ('h'). Thanks
