### ISSUE TITLE
Feature Request: show solutions of past puzzles

### ISSUE THREAD

**Issue by manevarthe** [DevangThakkar/wordle_archive#29]
When I solve a puzzle and come back to the same after some time, it should show the word that I solved. Right now, it only shows that I just solved the puzzle.

**Comment by no-stack-dub-sack** [comment]
Are you accepting PRs? I came here to open this issue as well as I keep losing track of the last puzzle I solves. Though maybe this could also be combined with the option to clear the solution if someone wants to resolve and/or the suggestion from #21 so there's a permanent log of your history even if you clear the solution from SC already solved Wordle.

Thoughts?

**Comment by DevangThakkar** [comment]
Sure, it would be great if you could work on this @no-stack-dub-sack! I just haven't had the time to do this.

**Comment by no-stack-dub-sack** [comment]
Great, I will try to work on it this weekend.

**Comment by no-stack-dub-sack** [comment]
@DevangThakkar just an update that this feature is underway. May take me until next weekend to finish it off. Will open the PR when ready.
