### ISSUE TITLE
[Feature request] Select a Wordle by number

### ISSUE THREAD

**Issue by Scimonster** [DevangThakkar/wordle_archive#3]
It would be great to be able to go to a specific Wordle by inputting the number.

Example usage: if a friend shares one they did from the archive and i want to compare how i do on that one.

**Comment by DevangThakkar** [comment]
Added this functionality for desktop, let me know if there are any issues with it. Closing this for now.

**Comment by Scimonster** [comment]
Thanks! I think having random also is good though, either as its own button, or possibly as the first option in the dropdown.

**Comment by DevangThakkar** [comment]
Adding it to the drop-down is a great idea, thanks! I'll do that.

**Comment by DevangThakkar** [comment]
Added the random option to the dropdown in desktop mode. Thanks for the suggestion @Scimonster , closing this for now!

**Comment by Scimonster** [comment]
Awesome, thanks for doing this!

**Comment by llbarrows** [comment]
When I enter all vowels to start nothing happens
