### ISSUE TITLE
Extra text block got created for unknown reason

### ISSUE THREAD

**Issue by harshithjv** [DevangThakkar/wordle_archive#31]
I don't know how but extra block got created.  Attached the screenshots:
![image](https://user-images.githubusercontent.com/809278/152489601-35ed86ba-044b-44d8-b1cd-96bb15ac3021.png)

![image](https://user-images.githubusercontent.com/809278/152490272-4ac58d44-0c15-41d5-b8f2-99039fc77f6e.png)

I just deleted the text block from developer tools and continued to play.

**Comment by DevangThakkar** [comment]
Hmm, that is very weird! I honestly have no idea how this happened but it seems pretty innocuous if it's not reproducible/recurring. Thanks for reporting it nevertheless!
