### ISSUE TITLE
multiple occurrences of same letter not handled properly

### ISSUE THREAD

**Issue by AdithyaPrabhu** [DevangThakkar/wordle_archive#34]
<img width="806" alt="Screenshot 2022-02-08 at 9 21 24 AM" src="https://user-images.githubusercontent.com/30821949/152915159-389098b0-f236-4818-af4a-373ab0337019.png">

**Comment by DevangThakkar** [comment]
Hi, the protocol for this is the same as the official Wordle. If a letter is in the correct place, it is marked as green. If you repeat a letter, the repeated letter in the wrong place will only be marked yellow if the letter is also in another place in the word. Closing this for now.
