### ISSUE TITLE
Feature Request: indicate which puzzles have been completed

### ISSUE THREAD

**Issue by chrisr29** [DevangThakkar/wordle_archive#39]
I’d like to be able to tell where I left off (starting with puzzle 1) so I don’t repeat a puzzle. Or if I do them randomly, which one I’ve completed already. Thanks so much for creating this!

**Comment by becarpenter** [comment]
Also thanks. But a friendly amendment to this issue: provide a feature such that it automatically presents the next one that you haven't solved. Like https://www.devangthakkar.com/wordle_archive/?next
@chrisr29 : my pro tip is to use the next button repeatedly until it finds a fresh one for you.

**Comment by DevangThakkar** [comment]
Hi, the archive should now show which ones you have already done in the `Choose` menu, along with how many turns it took you! Closing this for now!

**Comment by chrisr29** [comment]
Thank you very much. I really enjoy your game.

**Comment by becarpenter** [comment]
So cool. Thanks.
