### ISSUE TITLE
Controls are a little wonky on desktop

### ISSUE THREAD

**Issue by ddejohn** [DevangThakkar/wordle_archive#4]
![image](https://user-images.githubusercontent.com/35853209/149387629-b70b7bdb-fe3c-40c9-b799-18ac69263726.png)

Alternatively, you could use media playback symbols:

| first          | previous | random  | next         | last       |
|----------------|----------|---------|--------------|------------|
| previous track | rewind   | shuffle | fast forward | next track |

**Comment by DevangThakkar** [comment]
Fixed this, let me know if there are any issues with it. Closing this for now.
