### ISSUE TITLE
Wrong word for puzzle 117

### ISSUE THREAD

**Issue by MsAnthropic** [DevangThakkar/wordle_archive#47]
Puzzle 117 gave me the letters  _outh and when I inevitably failed it said the answer was ought. I don't know anything about coding, but I thought you might want to fix it. I tried to attach the screenshots I took, but it doesn't look like it worked? Sorry I'm not more help... 
![Screenshot_20220304-200709_Chrome](https://user-images.githubusercontent.com/100984519/156867784-d02597fc-8e14-4b9d-a672-2bb6a09c5e6c.jpg)
![Screenshot_20220304-200936_Chrome](https://user-images.githubusercontent.com/100984519/156867787-e61a4934-7e5a-4b2c-80a6-fafb7ef6947c.jpg)

**Comment by Nathdsgfiugaoiysfnhuah** [comment]
Yellow means right letter wrong spot, everything worked as it should

**Comment by DevangThakkar** [comment]
@Nathdsgfiugaoiysfnhuah is correct. Closing this!
