### ISSUE TITLE
Feature Request: Allow a puzzle number in the future / after today

### ISSUE THREAD

**Issue by LanMan04** [DevangThakkar/wordle_archive#48]
My friends and I like to play "Night Wordle" where we do a second word in the evening, and we always set the day to 1000 days in the future from today.  So if today's puzzle 262, "Night Wordle" is 1262.

Would you be willing to (in essence) eliminate like 44 of App.js?  This line checks if the number is in "the future" or not, and sets it to today if so.  I'd love to be able to set any day I want, including in the future.

**Comment by DevangThakkar** [comment]
Hi! I want the archive to be an archive in the truest sense and only allow past words, so this sadly won't be possible. Closing this for now.
