### ISSUE TITLE
Wordle # seems to be 1 behind

### ISSUE THREAD

**Issue by fieldlab** [DevangThakkar/wordle_archive#51]
The latest Wordle archive says 283 but the NYT equivalent says 284. This causes people to do what they believe to be yesterday's puzzle and communicate the solution to today's puzzle. Does this have to do with time zones?

A feature request would be to include the date of the NYT puzzle with the number- something conspicuously missing from the NYT site.

**Comment by DevangThakkar** [comment]
Hi, this happens when NYT removes words from its list - it removed a word from its list recently and I've updated my list to be exactly the same as theirs. It should hopefully be okay now. Let me know if it still isn't - closing this for now.
