### ISSUE TITLE
Game state limited to 500, answers list is in the thousands.

### ISSUE THREAD

**Issue by bobpaul** [DevangThakkar/wordle_archive#60]
https://github.com/DevangThakkar/wordle_archive/blob/9ccb1b6295161df72be70013071b20efed0de8f0/src/App.js#L195
```
  const [gameStateList, setGameStateList] = useLocalStorage(
    'gameStateList',
    Array(500).fill({ state: initialStates.gameState, board: null })
  )
```

This causes an uncaught exception which is due to Array index out of bounds. This should probably be set to `wordle_answers.length`, but the array also needs to be grown if the `wordle_answers` array is updated.

**Comment by DevangThakkar** [comment]
Hi @bobpaul , thank you for opening this issue. I stopped working on this repo in May 2022 when the NYT made me shut the archive down. Feel free to create a fork and update it needed. :)
