### ISSUE TITLE
Darkmode doesn't fill screen

### ISSUE THREAD

**Issue by ddejohn** [DevangThakkar/wordle_archive#7]
Desktop, Firefox 96.0.1 (64-bit)

Screenshot:

![image](https://user-images.githubusercontent.com/35853209/149643946-5849916a-5731-4829-b3b9-05d76354ee0d.png)

Minor feature request, put the darkmode switch directly on the home page, halving the number of clicks it takes to switch to the mode.

**Comment by DevangThakkar** [comment]
Could you check now? I think my new code should fix this issue.

**Comment by DevangThakkar** [comment]
Regarding the dark mode switch, I think I'm going to let it be where it is. I don't expect people to toggle it often enough to warrant the feature.

**Comment by DevangThakkar** [comment]
Closing this for now.
