### ISSUE TITLE
Buttons First and Last not visible in mobile View

### ISSUE THREAD

**Issue by ghanisch** [DevangThakkar/wordle_archive#8]
I can see the three middle buttons only on my phone.

Would be nice if one could swipe the button-row to the left or if the buttons are distributed to two rows if resolution is to small.

The only workaround on a phone is to switch to "desktop view" to reach the side buttons.

Or How about a dropdown menu on the number to reach older wordles?! Wouldnt need space!

**Comment by DevangThakkar** [comment]
Yes, that is what I had before - the mobile version only had the three buttons. Thank you for your request, I have added more navigation options to the mobile version, including a number drop-down. Hope that helps, closing this for now.
